Controllers/AdminBagrainsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _7semester_ASP_FirstTask.Models;

namespace _7semester_ASP_FirstTask.Controllers
{
	public class AdminBagrainsController : Controller
	{
		private readonly ApplicationContext _context;

		public AdminBagrainsController(ApplicationContext context)
		{
			_context = context;
		}

		// GET: AdminBagrains
		public async Task<IActionResult> Index(string skinTone, int master = 0, int page = 1,
			SortState sortOrder = SortState.SkinToneAsc)
		{
			int pageSize = 3;

			//фильтрация
			IQueryable<Slave> slaves = _context.Slaves.Include(x => x.Master);

			if (master != 0)
			{
				slaves = slaves.Where(p => p.MasterId == master);
			}
			if (!string.IsNullOrEmpty(skinTone))
			{
				slaves = slaves.Where(p => p.SkinTone == skinTone);
			}

			// сортировка
			switch (sortOrder)
			{
				case SortState.SkinToneDesc:
					slaves = slaves.OrderByDescending(s => s.SkinTone);
					break;
				case SortState.AgeAsc:
					slaves = slaves.OrderBy(s => s.Age);
					break;
				case SortState.AgeDesc:
					slaves = slaves.OrderByDescending(s => s.Age);
					break;
				case SortState.MasterAsc:
					slaves = slaves.OrderBy(s => s.Master!.Name);
					break;
				case SortState.MasterDesc:
					slaves = slaves.OrderByDescending(s => s.Master!.Name);
					break;
				default:
					slaves = slaves.OrderBy(s => s.SkinTone);
					break;
			}

			// пагинация
			var count = await slaves.CountAsync();
			var items = await slaves.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

			// формируем модель представления
			BagrainsViewModel viewModel = new BagrainsViewModel(
			items,
				new PageViewModel(count, page, pageSize),
				new FilterViewModel(await _context.Masters.ToListAsync(), master, skinTone),
				new SortViewModel(sortOrder)
			);
			return View(viewModel);
		}

		// GET: AdminBagrains/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.Slaves == null)
			{
				return NotFound();
			}

			var slave = await _context.Slaves
				.Include(s => s.Master)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (slave == null)
			{
				return NotFound();
			}

			return View(slave);
		}

		// GET: AdminBagrains/Create
		public IActionResult Create()
		{
			ViewData["MasterId"] = new SelectList(_context.Masters, "Id", "Name");
			return View();
		}

		// POST: AdminBagrains/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Price,Age,SkinTone,MasterId")] Slave slave)
		{
			if (ModelState.IsValid)
			{
				_context.Add(slave);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			ViewData["MasterId"] = new SelectList(_context.Masters, "Id", "Id", slave.MasterId);
			return View(slave);
		}

		// GET: AdminBagrains/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.Slaves == null)
			{
				return NotFound();
			}

			var slave = await _context.Slaves.FindAsync(id);
			if (slave == null)
			{
				return NotFound();
			}
			ViewData["MasterId"] = new SelectList(_context.Masters, "Id", "Name", slave.MasterId);
			return View(slave);
		}

		// POST: AdminBagrains/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Price,Age,SkinTone,MasterId")] Slave slave)
		{
			if (id != slave.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(slave);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!SlaveExists(slave.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewData["MasterId"] = new SelectList(_context.Masters, "Id", "Id", slave.MasterId);
			return View(slave);
		}

		// GET: AdminBagrains/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.Slaves == null)
			{
				return NotFound();
			}

			var slave = await _context.Slaves
				.Include(s => s.Master)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (slave == null)
			{
				return NotFound();
			}

			return View(slave);
		}

		// POST: AdminBagrains/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.Slaves == null)
			{
				return Problem("Entity set 'ApplicationContext.Slaves'  is null.");
			}
			var slave = await _context.Slaves.FindAsync(id);
			if (slave != null)
			{
				_context.Slaves.Remove(slave);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool SlaveExists(int id)
		{
			return _context.Slaves.Any(e => e.Id == id);
		}
	}
}

Views/Admin/UserCreate.cshtml
@model _7semester_ASP_FirstTask.Models.User

@{
	ViewData["Title"] = "UserCreate";
}

<h1>UserCreate</h1>

<h4>User</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="UserCreate">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="login" class="control-label"></label>
				<input asp-for="login" class="form-control" />
				<span asp-validation-for="login" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="password" class="control-label"></label>
				<input asp-for="password" class="form-control" />
				<span asp-validation-for="password" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Country" class="control-label"></label>
				<select asp-for="Country" class="form-control">
					<option value="Ukraine">Ukraine</option>
					<option value="Spain">Spain</option>
				</select>
				<span asp-validation-for="Country" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="UserCreate" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="UserIndex">Back to List</a>
</div>

Views/Admin/UserDelete.cshtml
@model _7semester_ASP_FirstTask.Models.User

@{
    ViewData["Title"] = "UserDelete";
}

<h1>UserDelete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.login)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.login)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.password)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
    </dl>
    
    <form asp-action="UserDelete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="UserDelete" class="btn btn-danger" /> |
        <a asp-action="UserIndex">Back to List</a>
    </form>
</div>

Views/Admin/UserDetails.cshtml
@model _7semester_ASP_FirstTask.Models.User

@{
    ViewData["Title"] = "UserDetails";
}

<h1>UserDetails</h1>

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.login)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.login)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="UserEdit" asp-route-id="@Model?.Id">UserEdit</a> |
    <a asp-action="UserIndex">Back to List</a>
</div>

Views/Admin/UserEdit.cshtml
@model _7semester_ASP_FirstTask.Models.User

@{
	ViewData["Title"] = "UserEdit";
}

<h1>UserEdit</h1>

<h4>User</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="UserEdit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id" />
			<div class="form-group">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="login" class="control-label"></label>
				<input asp-for="login" class="form-control" />
				<span asp-validation-for="login" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="password" class="control-label"></label>
				<input asp-for="password" class="form-control" />
				<span asp-validation-for="password" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Country" class="control-label"></label>
				<select asp-for="Country" class="form-control">
					<option value="Ukraine">Ukraine</option>
					<option value="Spain">Spain</option>
				</select>
				<span asp-validation-for="Country" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="UserIndex">Back to List</a>
</div>

Views/Admin/UserIndex.cshtml
@model IEnumerable<_7semester_ASP_FirstTask.Models.User>

@{
	ViewData["Title"] = "UserIndex";
}

<h2><a asp-controller="AdminBagrains" asp-action="Index">Bagrains</a></h2>

<p>
	<a asp-action="UserCreate">UserCreate New</a>
</p>
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.login)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.password)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Country)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.login)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.password)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Country)
				</td>
				<td>
					<a asp-action="UserEdit" asp-route-id="@item.Id">UserEdit</a> |
					<a asp-action="UserDetails" asp-route-id="@item.Id">UserDetails</a> |
					<a asp-action="UserDelete" asp-route-id="@item.Id">UserDelete</a>
				</td>
			</tr>
		}
	</tbody>
</table>